package com.sistemexico.schoolmanageralumntutor.infraestructure.configuration.error

class ErrorCode {
    companion object {
        //Cambiar a mayusculas, vol velocidad se tomo de go
        const val Id_Not_Found                  = "000"
        const val Null_Field                    = "001"
        const val Data_Mismatch                 = "002"
        const val Required_Data                 = "003"
        const val Incorrect_Format              = "004"
        const val Exceeded_Length               = "005"
        const val Minimun_Length                = "006"
        const val Duplicated_Field              = "007"
        const val Data_Not_Found                = "008"
        const val Primary_Key                   = "009"
        const val Error_database                = "010"
        const val Empty_Data_Request            = "011"
        const val Date_Range_Error              = "012"
        const val Invalid_Number                = "013"
        const val Existing_Data                 = "014"
        const val Transaction_Error             = "015"
        const val Not_Enough_Data               = "016"
        const val Parameter_No_Required         = "017"
        const val Existing_Record               = "018"
        const val Configuration_Error           = "019"
        const val Data_Records_Full             = "020"
        const val Overlapped_Hours              = "021"
        const val Miscalculation_Error          = "022"
        const val Date_Interval_Error           = "023"
        const val XML_Cfdi_Sealing_Error        = "024"
        const val XML_Script_Process            = "025"
        const val XML_Pack_Provider_Error       = "026"
        const val XML_DigitalFiscalStamp_Error  = "027"
        const val XML_Amounts_Exceeded          = "028"
        const val XML_Amounts_Negative          = "029"
        const val XML_Time_Elapsed              = "030"
        const val SOAP_Client_Error             = "031"
        const val CODE_IS_EXPIRED               = "032"
        const val TIME_IS_EXPIRED               = "033"
        const val CODE_IS_IN_USE                = "034"
        const val SEND_FAILED                   = "035"
        const val NOT_AVAILABLE                 = "036"
        const val Unauthorized  = "401"
        const val Successfull  = "999"
    }
}